"""The trust-store rule (email_mcp.tls) and the smtp driver's use of it.

Background (2026-09-14): python.org framework builds ship no root-CA
bundle, so ``ssl.create_default_context()`` holds zero anchors and every
verified handshake fails with CERTIFICATE_VERIFY_FAILED — the Gmail lane
broke the moment 2d6b9a9 switched peer verification on. Graph had solved
the same environment problem alone on 2026-07-29; now both lanes share
one rule, and the smtp driver names the certificate verdict instead of
suggesting the VPN.

Two layers: unit tests pin the source-selection rule and the error
mapping with monkeypatched seams; the real-handshake tests drive the
driver's own ``_connect`` against a local TLS SMTP server with a test CA
generated by the ``openssl`` CLI — the only way to prove verification
happens against an actual chain (the mocked context tests cannot).
"""
from __future__ import annotations

import shutil
import socket
import ssl
import subprocess
import threading
from pathlib import Path

import pytest

from email_mcp import codes, tls
from email_mcp.transports import SendError
from email_mcp.transports import smtp as smtp_mod
from email_mcp.transports.smtp import SmtpTransport


# --------------------------------------------------------------------- #
# the rule, unit level                                                   #
# --------------------------------------------------------------------- #

@pytest.fixture
def no_env(monkeypatch):
    monkeypatch.delenv("SSL_CERT_FILE", raising=False)
    monkeypatch.delenv("SSL_CERT_DIR", raising=False)


def test_framework_python_without_a_store_falls_back_to_certifi(
    monkeypatch, no_env,
):
    """The observed Gmail failure: default paths absent → certifi's bundle
    is loaded and reported; verification stays strict."""
    monkeypatch.setattr(tls, "_system_store", lambda: (None, None))
    ctx = tls.client_context()
    info = tls.describe(ctx)
    assert info["source"] == tls.SOURCE_CERTIFI
    assert info["roots"] > 0
    assert ctx.verify_mode == ssl.CERT_REQUIRED and ctx.check_hostname
    assert not tls.empty(ctx)


def test_a_default_hashed_directory_is_used_even_when_it_reads_empty(
    monkeypatch, no_env, tmp_path,
):
    """A default capath is a hashed directory: it loads lazily and reads
    zero anchors until a handshake touches it. That is a usable store,
    not a missing one — certifi must not be piled on top."""
    capath = tmp_path / "certs"
    capath.mkdir()
    (capath / "deadbeef.0").write_text("placeholder entry\n")
    monkeypatch.setattr(tls, "_system_store", lambda: (None, str(capath)))
    calls = []
    monkeypatch.setattr(tls, "_certifi_bundle",
                        lambda: calls.append(1) or None)
    ctx = tls.client_context()
    assert tls.describe(ctx) == {"roots": 0, "source": tls.SOURCE_SYSTEM}
    assert calls == []  # never consulted


def test_a_default_cafile_that_yields_no_anchor_falls_through_to_certifi(
    monkeypatch, no_env, tmp_path,
):
    """Different from a lazy directory: a default cafile that exists but
    holds no CA certificate is the empty-default install, and leaving it
    as "system" would suppress the fallback forever (and regress Graph,
    which used to reach certifi in exactly this state)."""
    bundle = tmp_path / "cert.pem"
    bundle.write_text("# no certificates in here\n")
    monkeypatch.setattr(tls, "_system_store", lambda: (str(bundle), None))
    ctx = tls.client_context()
    info = tls.describe(ctx)
    assert info["source"] == tls.SOURCE_CERTIFI and info["roots"] > 0


def test_system_store_seam_ignores_paths_that_exist_but_are_empty(
    monkeypatch, tmp_path,
):
    """ssl.get_default_verify_paths() can name an empty file and an empty
    directory (a bare OpenSSL layout with nothing installed); neither
    is usable. A directory with an entry is."""
    empty_file = tmp_path / "cert.pem"
    empty_file.write_text("")
    empty_dir = tmp_path / "certs"
    empty_dir.mkdir()
    fake = ssl.DefaultVerifyPaths(
        cafile=None, capath=None,
        openssl_cafile_env="SSL_CERT_FILE", openssl_cafile=str(empty_file),
        openssl_capath_env="SSL_CERT_DIR", openssl_capath=str(empty_dir))
    monkeypatch.setattr(tls.ssl, "get_default_verify_paths", lambda: fake)
    assert tls._system_store() == (None, None)
    (empty_dir / "deadbeef.0").write_text("x")
    assert tls._system_store() == (None, str(empty_dir))
    missing = fake._replace(openssl_cafile="/nonexistent/cert.pem",
                            openssl_capath="/nonexistent/certs")
    monkeypatch.setattr(tls.ssl, "get_default_verify_paths", lambda: missing)
    assert tls._system_store() == (None, None)


def test_operator_env_is_honoured_and_never_overridden(monkeypatch, tmp_path):
    """SSL_CERT_FILE / SSL_CERT_DIR win outright — even over a broken or
    empty bundle. Explicit trust configuration is the operator's call;
    adding certifi behind their back would widen trust silently."""
    empty_bundle = tmp_path / "empty.pem"
    empty_bundle.write_text("")
    monkeypatch.setenv("SSL_CERT_FILE", str(empty_bundle))
    monkeypatch.delenv("SSL_CERT_DIR", raising=False)
    monkeypatch.setattr(tls, "_system_store", lambda: (None, None))
    calls = []
    monkeypatch.setattr(tls, "_certifi_bundle",
                        lambda: calls.append(1) or None)
    ctx = tls.client_context()
    info = tls.describe(ctx)
    assert info["source"] == tls.SOURCE_ENV
    assert info["roots"] == 0          # broken on purpose, still honoured
    assert not tls.empty(ctx)          # configured ≠ absent: let the
    assert calls == []                 # handshake decide, no certifi


def test_explicitly_empty_env_values_are_a_configuration_too(monkeypatch):
    """SSL_CERT_FILE='' SSL_CERT_DIR='' is how an operator says "trust
    nothing from the defaults". Presence counts, not truthiness: no
    certifi, zero roots, and the handshake fails as configured."""
    import certifi
    monkeypatch.setenv("SSL_CERT_FILE", "")
    monkeypatch.setenv("SSL_CERT_DIR", "")
    calls = []
    monkeypatch.setattr(tls, "_certifi_bundle",
                        lambda: calls.append(1) or None)
    monkeypatch.setattr(tls, "_system_store",
                        lambda: (certifi.where(), None))  # must stay unused
    ctx = tls.client_context()
    assert tls.describe(ctx) == {"roots": 0, "source": tls.SOURCE_ENV}
    assert calls == []
    assert ctx.verify_mode == ssl.CERT_REQUIRED and ctx.check_hostname


def test_verification_settings_match_the_running_interpreter(monkeypatch, no_env):
    """Only the trust loading is ours. verify_flags (3.13+ adds
    VERIFY_X509_STRICT and VERIFY_X509_PARTIAL_CHAIN; older interpreters
    keep theirs), options and the TLS version bounds must equal what
    create_default_context() sets on THIS interpreter — parity, not a
    hard-coded flag list, and no silent weakening on either side."""
    import certifi
    ref = ssl.create_default_context()
    monkeypatch.setattr(tls, "_system_store", lambda: (None, None))
    for ctx in (tls.client_context(), tls.client_context(cafile=certifi.where())):
        assert ctx.verify_mode == ssl.CERT_REQUIRED and ctx.check_hostname
        assert ctx.verify_flags == ref.verify_flags
        assert ctx.options == ref.options
        assert (ctx.minimum_version, ctx.maximum_version) == \
            (ref.minimum_version, ref.maximum_version)


def _spy_load(monkeypatch):
    seen: list[tuple] = []
    real = tls._load

    def spy(ctx, cafile, capath):
        seen.append((cafile, capath))
        return real(ctx, cafile, capath)

    monkeypatch.setattr(tls, "_load", spy)
    return seen


def test_only_ssl_cert_dir_keeps_the_default_cafile(monkeypatch, tmp_path):
    """OpenSSL semantics: each variable replaces its own component. A
    private hashed directory added through SSL_CERT_DIR must not throw
    away the public roots in the default cafile."""
    import certifi
    extra = tmp_path / "private"
    extra.mkdir()
    monkeypatch.setenv("SSL_CERT_DIR", str(extra))
    monkeypatch.delenv("SSL_CERT_FILE", raising=False)
    monkeypatch.setattr(tls, "_system_store", lambda: (certifi.where(), None))
    seen = _spy_load(monkeypatch)
    ctx = tls.client_context()
    info = tls.describe(ctx)
    assert info["source"] == tls.SOURCE_ENV and info["roots"] > 0
    assert seen == [(certifi.where(), str(extra))]


def test_only_ssl_cert_file_keeps_the_default_capath(monkeypatch, tmp_path):
    import certifi
    default_dir = tmp_path / "certs"
    default_dir.mkdir()
    (default_dir / "deadbeef.0").write_text("x")
    monkeypatch.setenv("SSL_CERT_FILE", certifi.where())
    monkeypatch.delenv("SSL_CERT_DIR", raising=False)
    monkeypatch.setattr(tls, "_system_store", lambda: (None, str(default_dir)))
    seen = _spy_load(monkeypatch)
    ctx = tls.client_context()
    assert tls.describe(ctx)["source"] == tls.SOURCE_ENV
    assert seen == [(certifi.where(), str(default_dir))]


def test_explicit_cafile_argument_wins(tmp_path, monkeypatch):
    monkeypatch.setenv("SSL_CERT_FILE", "/nonexistent/ignored.pem")
    import certifi
    ctx = tls.client_context(cafile=certifi.where())
    info = tls.describe(ctx)
    assert info["source"] == tls.SOURCE_EXPLICIT and info["roots"] > 0


def test_no_store_anywhere_is_empty_and_names_the_local_remedy(
    monkeypatch, no_env,
):
    monkeypatch.setattr(tls, "_system_store", lambda: (None, None))
    monkeypatch.setattr(tls, "_certifi_bundle", lambda: None)
    ctx = tls.client_context()
    assert tls.describe(ctx) == {"roots": 0, "source": tls.SOURCE_NONE}
    assert tls.empty(ctx)
    text = tls.remedy(ctx)
    assert "certifi" in text and "Install Certificates.command" in text
    assert "VPN" not in text


def _verify_error(code: int, message: str) -> ssl.SSLCertVerificationError:
    e = ssl.SSLCertVerificationError(
        1, f"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: "
           f"{message} (_ssl.c:992)")
    e.verify_code = code
    e.verify_message = message
    return e


@pytest.mark.parametrize("code, message, expect", [
    (20, "unable to get local issuer certificate", "no issuer"),
    (19, "self-signed certificate in certificate chain", "no issuer"),
    (10, "certificate has expired", "validity period"),
    (62, "Hostname mismatch, certificate is not valid for 'x'", "host name"),
    (7, "certificate signature failure", "verification failed"),
])
def test_failure_line_carries_the_verdict_and_a_matching_hint(
    monkeypatch, no_env, code, message, expect,
):
    """OpenSSL's verify_message/verify_code, the store that judged it,
    and a hint that follows from THAT verdict — never a diagnosis
    (interception, wrong host) asserted from a nonzero root count."""
    monkeypatch.setattr(tls, "_system_store", lambda: (None, None))
    ctx = tls.client_context()
    line = tls.failure(ctx, _verify_error(code, message))
    assert message in line and f"verify code {code}" in line
    assert "roots loaded from certifi" in line
    assert expect in line
    assert "VPN" not in line


# --------------------------------------------------------------------- #
# the driver, mocked wire                                                #
# --------------------------------------------------------------------- #

def _smtp(**kw) -> SmtpTransport:
    defaults = dict(identity="gmail", from_addr="g@example.org",
                    host="smtp.example.org", keychain="email-mcp-g")
    defaults.update(kw)
    return SmtpTransport(**defaults)


_RAW = (b"From: g@example.org\r\nTo: a@example.org\r\nSubject: s\r\n"
        b"Message-ID: <m@x>\r\n\r\nbody\r\n")


def _rejecting_smtp_cls(exc: BaseException):
    """smtplib.SMTP stand-in whose STARTTLS fails verification."""
    class Fake:
        instances: list = []

        def __init__(self, host, port, timeout=None, context=None):
            self.calls: list = []
            self.closed = False
            Fake.instances.append(self)

        def starttls(self, context=None):
            self.calls.append(("starttls", context))
            raise exc

        def ehlo(self):
            self.calls.append(("ehlo",))

        def login(self, *a):
            self.calls.append(("login",))

        def sendmail(self, *a):
            self.calls.append(("sendmail",))

        def close(self):
            self.closed = True

        def quit(self):
            self.calls.append(("quit",))

    return Fake


def test_deliver_maps_verification_failure_to_transport_unavailable(
    monkeypatch, no_env,
):
    """Not delivery_failed with a VPN hint: nothing was sent, no secret
    was spoken, and the same handshake fails on every retry. The lane is
    unavailable and the message says why, in OpenSSL's words."""
    monkeypatch.setattr(tls, "_system_store", lambda: (None, None))
    Fake = _rejecting_smtp_cls(
        _verify_error(20, "unable to get local issuer certificate"))
    monkeypatch.setattr(smtp_mod.smtplib, "SMTP", Fake)
    monkeypatch.setattr(smtp_mod, "_read_keychain", lambda item, account: "pw")
    with pytest.raises(SendError) as ei:
        _smtp(port=587).deliver(_RAW, "g@example.org", ["a@example.org"])
    assert ei.value.code == codes.TRANSPORT_UNAVAILABLE
    text = str(ei.value)
    assert "[gmail/smtp] TLS certificate verification of smtp.example.org:587 failed" in text
    assert "unable to get local issuer certificate" in text
    assert "VPN" not in text
    fake = Fake.instances[0]
    assert fake.closed                      # _connect closed what it opened
    assert ("login",) not in fake.calls and ("sendmail",) not in fake.calls


def test_ensure_reports_the_certificate_verdict_without_auth(
    monkeypatch, no_env,
):
    monkeypatch.setattr(tls, "_system_store", lambda: (None, None))
    Fake = _rejecting_smtp_cls(_verify_error(10, "certificate has expired"))
    monkeypatch.setattr(smtp_mod.smtplib, "SMTP", Fake)
    monkeypatch.setattr(smtp_mod, "_read_keychain", lambda item, account: "pw")
    t = _smtp(port=587)
    assert t.ensure() is False
    assert "certificate has expired" in t.last_ensure_error
    assert "validity period" in t.last_ensure_error
    assert ("login",) not in Fake.instances[0].calls


def test_healthcheck_fix_names_the_certificate_not_the_vpn(
    monkeypatch, no_env,
):
    monkeypatch.setattr(tls, "_system_store", lambda: (None, None))
    Fake = _rejecting_smtp_cls(
        _verify_error(20, "unable to get local issuer certificate"))
    monkeypatch.setattr(smtp_mod.smtplib, "SMTP", Fake)
    monkeypatch.setattr(smtp_mod, "_read_keychain", lambda item, account: "pw")
    t = _smtp(port=587)
    hc = t.healthcheck()
    assert hc["ok"] is False
    assert hc["trust_store"] == tls.describe(t._ctx)   # the judging one
    assert hc["trust_store"]["source"] == tls.SOURCE_CERTIFI
    assert hc["trust_store"]["roots"] > 0
    assert "unable to get local issuer certificate" in hc["error"]
    assert "no issuer" in hc["fix"]
    assert "VPN" not in hc["fix"] and "ssh_sendmail" not in hc["fix"]


def test_empty_store_is_refused_before_any_connection(monkeypatch, no_env):
    """Zero anchors and none configured: connecting is pointless and the
    remedy is local. Refuse up front, before the socket, the password or
    the message."""
    monkeypatch.setattr(tls, "_system_store", lambda: (None, None))
    monkeypatch.setattr(tls, "_certifi_bundle", lambda: None)
    monkeypatch.setattr(
        smtp_mod.smtplib, "SMTP",
        lambda *a, **k: pytest.fail("must not connect with an empty store"))
    monkeypatch.setattr(smtp_mod, "_read_keychain", lambda item, account: "pw")
    t = _smtp(port=587)
    with pytest.raises(SendError) as ei:
        t.deliver(_RAW, "g@example.org", ["a@example.org"])
    assert ei.value.code == codes.TRANSPORT_UNAVAILABLE
    assert "certifi" in str(ei.value)
    assert t.ensure() is False and "certifi" in t.last_ensure_error
    hc = t.healthcheck()
    assert hc["ok"] is False and "certifi" in hc["fix"]


# --------------------------------------------------------------------- #
# the driver, real handshakes                                            #
# --------------------------------------------------------------------- #

_OPENSSL = shutil.which("openssl")


@pytest.fixture(scope="module")
def pki(tmp_path_factory):
    """A test CA and a localhost leaf (SAN DNS:localhost), via the openssl
    CLI, plus a hashed directory for the lazy-capath case."""
    if not _OPENSSL:
        pytest.skip("openssl CLI not available")
    d = tmp_path_factory.mktemp("pki")
    ca_cnf = d / "ca.cnf"
    ca_cnf.write_text(
        "[req]\ndistinguished_name=dn\nx509_extensions=v3\nprompt=no\n"
        "[dn]\nCN=email-mcp test CA\n"
        "[v3]\nbasicConstraints=critical,CA:TRUE\n"
        "keyUsage=critical,keyCertSign,cRLSign\n"
        "subjectKeyIdentifier=hash\n")
    leaf_cnf = d / "leaf.cnf"
    leaf_cnf.write_text(
        "[req]\ndistinguished_name=dn\nprompt=no\n[dn]\nCN=localhost\n")
    ext = d / "leaf.ext"
    ext.write_text(
        "subjectAltName=DNS:localhost\nbasicConstraints=CA:FALSE\n"
        "keyUsage=digitalSignature,keyEncipherment\n"
        "extendedKeyUsage=serverAuth\n"
        "authorityKeyIdentifier=keyid\n")
    steps = [
        [_OPENSSL, "req", "-x509", "-newkey", "rsa:2048", "-nodes", "-days", "2",
         "-keyout", str(d / "ca.key"), "-out", str(d / "ca.pem"),
         "-config", str(ca_cnf)],
        [_OPENSSL, "req", "-newkey", "rsa:2048", "-nodes",
         "-keyout", str(d / "leaf.key"), "-out", str(d / "leaf.csr"),
         "-config", str(leaf_cnf)],
        [_OPENSSL, "x509", "-req", "-days", "2", "-in", str(d / "leaf.csr"),
         "-CA", str(d / "ca.pem"), "-CAkey", str(d / "ca.key"),
         "-CAcreateserial", "-out", str(d / "leaf.pem"),
         "-extfile", str(ext)],
    ]
    for cmd in steps:
        r = subprocess.run(cmd, capture_output=True, text=True)
        if r.returncode:
            pytest.skip(f"openssl could not build the test PKI: {r.stderr[-300:]}")
    # A second chain: root -> intermediate -> leaf2, for the partial-chain
    # parity case (trusting only the intermediate).
    inter_ext = d / "inter.ext"
    inter_ext.write_text(
        "basicConstraints=critical,CA:TRUE,pathlen:0\n"
        "keyUsage=critical,keyCertSign,cRLSign\n"
        "subjectKeyIdentifier=hash\nauthorityKeyIdentifier=keyid\n")
    inter_cnf = d / "inter.cnf"
    inter_cnf.write_text(
        "[req]\ndistinguished_name=dn\nprompt=no\n[dn]\nCN=email-mcp test intermediate\n")
    steps = [
        [_OPENSSL, "req", "-newkey", "rsa:2048", "-nodes",
         "-keyout", str(d / "inter.key"), "-out", str(d / "inter.csr"),
         "-config", str(inter_cnf)],
        [_OPENSSL, "x509", "-req", "-days", "2", "-in", str(d / "inter.csr"),
         "-CA", str(d / "ca.pem"), "-CAkey", str(d / "ca.key"),
         "-CAcreateserial", "-out", str(d / "inter.pem"),
         "-extfile", str(inter_ext)],
        [_OPENSSL, "req", "-newkey", "rsa:2048", "-nodes",
         "-keyout", str(d / "leaf2.key"), "-out", str(d / "leaf2.csr"),
         "-config", str(leaf_cnf)],
        [_OPENSSL, "x509", "-req", "-days", "2", "-in", str(d / "leaf2.csr"),
         "-CA", str(d / "inter.pem"), "-CAkey", str(d / "inter.key"),
         "-CAcreateserial", "-out", str(d / "leaf2.pem"),
         "-extfile", str(ext)],
    ]
    for cmd in steps:
        r = subprocess.run(cmd, capture_output=True, text=True)
        if r.returncode:
            pytest.skip(f"openssl could not build the test PKI: {r.stderr[-300:]}")
    (d / "chain2.pem").write_bytes(
        (d / "leaf2.pem").read_bytes() + (d / "inter.pem").read_bytes())
    h = subprocess.run([_OPENSSL, "x509", "-hash", "-noout", "-in",
                        str(d / "ca.pem")], capture_output=True, text=True)
    hashed = d / "hashed"
    hashed.mkdir()
    (hashed / f"{h.stdout.strip()}.0").write_bytes((d / "ca.pem").read_bytes())
    return {"ca": d / "ca.pem", "leaf": d / "leaf.pem",
            "key": d / "leaf.key", "capath": hashed,
            "intermediate": d / "inter.pem",
            "chain2": d / "chain2.pem", "key2": d / "leaf2.key"}


class _TlsSmtpServer:
    """Just enough SMTP to reach the handshake: greets, EHLO, STARTTLS (or
    implicit TLS), then 250s everything and 221s QUIT. Records the
    commands it saw so a test can prove no AUTH ever happened.

    Patient on purpose (60 s): smtplib calls socket.getfqdn() between the
    greeting and the first command, and on some hosts (GitHub's macOS
    runners) reverse DNS makes that take tens of seconds. A 10 s server
    timeout there closed the conversation under the client — and a kept
    traceback then pinned the socket open, so the client saw a timeout
    rather than EOF. The error is stored as text, and the socket is shut
    down explicitly, so a failure is always visible as one."""

    TIMEOUT = 60

    def __init__(self, pki: dict, *, implicit: bool) -> None:
        self.ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
        self.ctx.load_cert_chain(str(pki["leaf"]), str(pki["key"]))
        self.implicit = implicit
        self.sock = socket.socket()
        self.sock.bind(("127.0.0.1", 0))
        self.sock.listen(1)
        self.sock.settimeout(self.TIMEOUT)
        self.port = self.sock.getsockname()[1]
        self.commands: list[bytes] = []
        self.handshake_error: str | None = None
        self.thread = threading.Thread(target=self._serve, daemon=True)
        self.thread.start()

    def _serve(self) -> None:
        try:
            conn, _ = self.sock.accept()
        except OSError:
            return
        conn.settimeout(self.TIMEOUT)
        f = None
        try:
            if self.implicit:
                conn = self.ctx.wrap_socket(conn, server_side=True)
            conn.sendall(b"220 test ESMTP\r\n")
            f = conn.makefile("rb")
            while True:
                line = f.readline()
                if not line:
                    return
                cmd = line.strip().upper()
                self.commands.append(cmd)
                if cmd.startswith(b"EHLO"):
                    conn.sendall(b"250-test\r\n250-STARTTLS\r\n"
                                 b"250 AUTH PLAIN LOGIN\r\n")
                elif cmd == b"STARTTLS":
                    conn.sendall(b"220 go ahead\r\n")
                    f.close()
                    conn = self.ctx.wrap_socket(conn, server_side=True)
                    f = conn.makefile("rb")
                elif cmd == b"QUIT":
                    conn.sendall(b"221 bye\r\n")
                    return
                else:
                    conn.sendall(b"250 ok\r\n")
        except BaseException as e:  # noqa: BLE001 — a rejected handshake
            self.handshake_error = repr(e)  # text: never pin the frame
        finally:
            for closer in ((f.close if f is not None else None),
                           lambda: conn.shutdown(socket.SHUT_RDWR),
                           conn.close):
                try:
                    if closer is not None:
                        closer()
                except OSError:
                    pass

    def close(self) -> None:
        self.sock.close()
        self.thread.join(timeout=self.TIMEOUT)


@pytest.fixture
def live(monkeypatch, pki):
    """Drive the driver's own _connect against a local server. Implicit
    TLS needs port 465 by the driver's rule, which we cannot bind: the
    real smtplib.SMTP_SSL is kept, only its port is redirected."""
    servers: list[_TlsSmtpServer] = []
    real_ssl = smtp_mod.smtplib.SMTP_SSL

    def run(host: str, *, implicit: bool, chain: dict | None = None):
        srv = _TlsSmtpServer(chain or pki, implicit=implicit)
        servers.append(srv)
        if implicit:
            monkeypatch.setattr(
                smtp_mod.smtplib, "SMTP_SSL",
                lambda h, p, timeout=None, context=None:
                    real_ssl(h, srv.port, timeout=timeout, context=context))
            t = _smtp(host=host, port=465)
        else:
            t = _smtp(host=host, port=srv.port)
        return t, srv

    monkeypatch.setattr(smtp_mod, "_read_keychain", lambda item, account: "pw")
    # smtplib names this host in EHLO via socket.getfqdn(), which can
    # take tens of seconds of reverse DNS on CI hosts; the name is
    # irrelevant to every assertion here, so pin it and keep CI fast.
    monkeypatch.setattr(socket, "getfqdn", lambda name="": "localhost")
    yield run
    for s in servers:
        s.close()


@pytest.mark.parametrize("implicit", [False, True], ids=["starttls", "implicit"])
def test_untrusted_chain_is_rejected_on_both_paths(live, monkeypatch, implicit):
    """certifi's bundle (the fallback in force here) does not know the
    test CA: the handshake must fail as a certificate verdict, before
    login, on STARTTLS and on implicit TLS alike."""
    monkeypatch.delenv("SSL_CERT_FILE", raising=False)
    monkeypatch.delenv("SSL_CERT_DIR", raising=False)
    monkeypatch.setattr(tls, "_system_store", lambda: (None, None))
    t, srv = live("localhost", implicit=implicit)
    assert t.ensure() is False
    assert "TLS certificate verification of localhost" in t.last_ensure_error
    assert "verify code" in t.last_ensure_error
    assert not any(c.startswith(b"AUTH") for c in srv.commands)


@pytest.mark.parametrize("implicit", [False, True], ids=["starttls", "implicit"])
def test_trusted_ca_via_env_is_accepted_and_ensure_never_logs_in(
    live, monkeypatch, pki, implicit,
):
    monkeypatch.setenv("SSL_CERT_FILE", str(pki["ca"]))
    monkeypatch.delenv("SSL_CERT_DIR", raising=False)
    t, srv = live("localhost", implicit=implicit)
    assert t.ensure() is True, t.last_ensure_error
    srv.close()
    assert not any(c.startswith((b"AUTH", b"MAIL", b"DATA"))
                   for c in srv.commands)
    assert b"QUIT" in srv.commands
    assert tls.describe(tls.client_context())["source"] == tls.SOURCE_ENV


def test_hostname_mismatch_is_rejected_even_with_a_trusted_ca(
    live, monkeypatch, pki,
):
    """The leaf is for DNS:localhost; connecting by address must fail on
    the name check — trust in the CA is not trust in the host."""
    monkeypatch.setenv("SSL_CERT_FILE", str(pki["ca"]))
    monkeypatch.delenv("SSL_CERT_DIR", raising=False)
    t, srv = live("127.0.0.1", implicit=False)
    assert t.ensure() is False
    err = t.last_ensure_error
    assert "TLS certificate verification of 127.0.0.1" in err
    assert "host name" in err or "Hostname mismatch" in err


def test_hashed_directory_reads_zero_roots_and_still_verifies(
    live, monkeypatch, pki,
):
    """SSL_CERT_DIR: OpenSSL loads a hashed directory lazily, so the
    store reads 0 roots before the first handshake — and verifies fine.
    A zero count must never be mistaken for an absent store. The cafile
    component is emptied explicitly so only the directory is in play
    on any host (SSL_CERT_DIR alone would keep the default cafile)."""
    monkeypatch.setenv("SSL_CERT_FILE", "")
    monkeypatch.setenv("SSL_CERT_DIR", str(pki["capath"]))
    ctx = tls.client_context()
    assert tls.describe(ctx) == {"roots": 0, "source": tls.SOURCE_ENV}
    assert not tls.empty(ctx)
    t, srv = live("localhost", implicit=False)
    assert t.ensure() is True, t.last_ensure_error
    # The context that judged the peer now shows what the handshake
    # loaded from the directory — that is the one the driver keeps.
    assert tls.describe(t._ctx) == {"roots": 1, "source": tls.SOURCE_ENV}


def test_intermediate_anchor_behaves_exactly_like_create_default_context(
    live, monkeypatch, pki,
):
    """Trusting ONLY the intermediate of a root -> intermediate -> leaf
    chain is accepted where the interpreter's create_default_context
    sets VERIFY_X509_PARTIAL_CHAIN (3.13+) and rejected where it does
    not. The driver must do exactly what the reference does on THIS
    interpreter — measured, not assumed, with one real handshake each."""
    chain = {"leaf": pki["chain2"], "key": pki["key2"]}
    ref = ssl.create_default_context(cafile=str(pki["intermediate"]))
    srv = _TlsSmtpServer(chain, implicit=True)
    try:
        with socket.create_connection(("127.0.0.1", srv.port), timeout=10) as raw:
            with ref.wrap_socket(raw, server_hostname="localhost"):
                ref_ok = True
    except ssl.SSLCertVerificationError:
        ref_ok = False
    finally:
        srv.close()
    assert ref_ok == bool(ref.verify_flags & ssl.VERIFY_X509_PARTIAL_CHAIN)

    monkeypatch.setenv("SSL_CERT_FILE", str(pki["intermediate"]))
    monkeypatch.setenv("SSL_CERT_DIR", "")  # nothing else, on any host
    for implicit in (True, False):
        t, srv = live("localhost", implicit=implicit, chain=chain)
        assert t.ensure() is ref_ok, t.last_ensure_error
        if not ref_ok:
            assert "verify code" in t.last_ensure_error
